#!/bin/bash
# Plan Index Manager - Auto-sync script
# Scans ~/.claude/plans/*.md and generates INDEX.md

set -eo pipefail

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$HOME/.claude/hooks/plans-sync-config.sh"

# Create default config if doesn't exist
if [[ ! -f "$CONFIG_FILE" ]]; then
    cat > "$CONFIG_FILE" <<'EOF'
#!/bin/bash
# Plan Index Manager Configuration
PLAN_INDEX_LANG="en"
PLANS_DIR="$HOME/.claude/plans"
EOF
fi

# Load config
source "$CONFIG_FILE"

# Override language if --lang flag provided
while [[ $# -gt 0 ]]; do
    case $1 in
        --lang)
            PLAN_INDEX_LANG="$2"
            # Update config file
            sed -i '' "s/PLAN_INDEX_LANG=.*/PLAN_INDEX_LANG=\"$2\"/" "$CONFIG_FILE"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

INDEX_FILE="$PLANS_DIR/INDEX.md"
TEMP_FILE="$PLANS_DIR/.index-temp.md"

# Localization strings
if [[ "$PLAN_INDEX_LANG" == "zh" ]]; then
    L_PRIORITY_HIGH="P0（高优）"
    L_PRIORITY_MED="P1（中优）"
    L_PRIORITY_LOW="P2（低优）"
    L_MORE="更多..."
    L_FOOTER_1="本文件由 \`~/.claude/hooks/plans-sync.sh\` 自动生成"
    L_FOOTER_2="触发时机：PlanModeEnd Hook"
    L_FOOTER_3="手动同步：\`bash ~/.claude/hooks/plans-sync.sh\`"
    L_STATUS_COMPLETED="已完成"
    L_STATUS_IN_PROGRESS="进行中"
    L_STATUS_PLANNING="规划中"
    L_STATUS_ONGOING="持续更新"
    L_UPDATED="已更新"
else
    L_PRIORITY_HIGH="P0 (High)"
    L_PRIORITY_MED="P1 (Medium)"
    L_PRIORITY_LOW="P2 (Low)"
    L_MORE="More..."
    L_FOOTER_1="This file is automatically generated by \`~/.claude/hooks/plans-sync.sh\`"
    L_FOOTER_2="Trigger: PlanModeEnd Hook"
    L_FOOTER_3="Manual sync: \`bash ~/.claude/hooks/plans-sync.sh\`"
    L_STATUS_COMPLETED="Completed"
    L_STATUS_IN_PROGRESS="In Progress"
    L_STATUS_PLANNING="Planning"
    L_STATUS_ONGOING="Ongoing"
    L_UPDATED="updated"
fi

# Extract metadata from plan file
# Output format: date|title|filename|priority|plan_status
extract_metadata() {
    local file="$1"
    local filename=$(basename "$file")

    # Skip INDEX.md itself
    [[ "$filename" == "INDEX.md" ]] && return 0

    # Extract title (first # heading)
    local title=$(grep -m 1 '^# ' "$file" 2>/dev/null | sed 's/^# //' || echo "Untitled")

    # Remove "Peer Review Report:" prefix if exists
    title=$(echo "$title" | sed 's/^Peer Review Report: //')

    # Extract file modification date
    local date=$(stat -f "%Sm" -t "%Y-%m-%d" "$file" 2>/dev/null || date +"%Y-%m-%d")

    # Try to extract priority from content
    local priority=$(grep -m 1 -iE '\*\*优先级\*\*.*P[0-2]|Priority.*P[0-2]|\*\*Priority\*\*.*P[0-2]' "$file" 2>/dev/null | grep -oE 'P[0-2]' || echo "P1")

    # Try to extract plan_status from content
    local plan_status="$L_STATUS_PLANNING"
    if grep -qiE '已完成|completed|done' "$file" 2>/dev/null; then
        plan_status="$L_STATUS_COMPLETED"
    elif grep -qiE '进行中|in progress|implementing' "$file" 2>/dev/null; then
        plan_status="$L_STATUS_IN_PROGRESS"
    elif grep -qiE '持续更新|ongoing|continuous' "$file" 2>/dev/null; then
        plan_status="$L_STATUS_ONGOING"
    fi

    echo "$date|$title|$filename|$priority|$plan_status"
}

# Generate INDEX.md
generate_index() {
    # Determine template path
    local template_file
    if [[ -f "$SCRIPT_DIR/../templates/INDEX.$PLAN_INDEX_LANG.md" ]]; then
        template_file="$SCRIPT_DIR/../templates/INDEX.$PLAN_INDEX_LANG.md"
    elif [[ -f "$HOME/.claude/hooks/templates/INDEX.$PLAN_INDEX_LANG.md" ]]; then
        template_file="$HOME/.claude/hooks/templates/INDEX.$PLAN_INDEX_LANG.md"
    else
        # Fallback: generate default header
        cat > "$TEMP_FILE" <<EOF
# Plans Index

> Last updated: AUTO_UPDATE_DATE
> Purpose: Quick search and restore planning files

## How to Use

Ask Claude Code:
- "Find Plan: [keyword]" — Search related plans
- "Restore Plan: [title]" — Load complete plan

---

## Plan List

| Date | Title | Filename | Priority | Status |
|------|------|----------|----------|--------|
EOF
    fi

    # Use template if found
    if [[ -n "$template_file" ]]; then
        cp "$template_file" "$TEMP_FILE"
    fi

    # Replace date
    sed -i '' "s/AUTO_UPDATE_DATE/$(date +"%Y-%m-%d")/" "$TEMP_FILE"

    # Scan all plan files and sort by date (descending)
    local plans_data=""
    for file in "$PLANS_DIR"/*.md; do
        [[ -f "$file" ]] || continue
        local metadata=$(extract_metadata "$file")
        [[ -n "$metadata" ]] && plans_data+="$metadata"$'\n'
    done

    # Sort by date (descending) and write to table
    echo "$plans_data" | sort -t'|' -k1 -r | while IFS='|' read -r date title filename priority plan_status; do
        [[ -z "$date" ]] && continue
        echo "| $date | $title | $filename | $priority | $plan_status |" >> "$TEMP_FILE"
    done || true

    # Add priority grouping section
    cat >> "$TEMP_FILE" <<EOF

---

## By Priority

### $L_PRIORITY_HIGH
EOF

    echo "$plans_data" | grep '|P0|' | sort -t'|' -k1 -r | while IFS='|' read -r date title filename priority plan_status; do
        echo "- $title" >> "$TEMP_FILE"
    done || true

    cat >> "$TEMP_FILE" <<EOF

### $L_PRIORITY_MED
EOF

    echo "$plans_data" | grep '|P1|' | sort -t'|' -k1 -r | head -10 | while IFS='|' read -r date title filename priority plan_status; do
        echo "- $title" >> "$TEMP_FILE"
    done || true

    echo "- $L_MORE" >> "$TEMP_FILE"

    cat >> "$TEMP_FILE" <<EOF

### $L_PRIORITY_LOW
EOF

    echo "$plans_data" | grep '|P2|' | sort -t'|' -k1 -r | head -5 | while IFS='|' read -r date title filename priority plan_status; do
        echo "- $title" >> "$TEMP_FILE"
    done || true

    echo "- $L_MORE" >> "$TEMP_FILE"

    # Add footer
    cat >> "$TEMP_FILE" <<EOF

---

## Maintenance

$L_FOOTER_1
- $L_FOOTER_2
- $L_FOOTER_3
EOF

    # Replace original file
    mv "$TEMP_FILE" "$INDEX_FILE"
    echo "✅ INDEX.md $L_UPDATED ($(date +"%Y-%m-%d %H:%M:%S"))"
}

# Main logic
main() {
    # Check if plans directory exists
    if [[ ! -d "$PLANS_DIR" ]]; then
        echo "⚠️  Plans directory not found: $PLANS_DIR"
        return 1
    fi

    # Generate index
    generate_index

    # Explicit success return
    return 0
}

# Execute
main "$@"
exit $?
